name: Java CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Cambia esto por la versión de Java que estés usando
          distribution: ''

      - name: Install dependencies
        run: ./gradlew build # Si usas Maven, cambia esto a `mvn install`

      - name: Run tests
        run: ./gradlew test # O `mvn test` si usas Maven

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest # O `mvn checkstyle:check` si usas Maven

